// Copyright Kamu Data, Inc. and contributors. All rights reserved.
//
// Use of this software is governed by the Business Source License
// included in the LICENSE file.
//
// As of the Change Date specified in that file, in accordance with
// the Business Source License, use of this software will be governed
// by the Apache License, Version 2.0.

// Generated with protoc-gen-tonic=0.4.1
// Generated with protoc-gen-prost=0.4.0
// Generated with protoc=libprotoc 29.3
// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RawQueryRequest {
    #[prost(bytes = "vec", tag = "1")]
    pub flatbuffer: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RawQueryResponse {
    #[prost(bytes = "vec", tag = "1")]
    pub flatbuffer: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TransformRequest {
    #[prost(bytes = "vec", tag = "1")]
    pub flatbuffer: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TransformResponse {
    #[prost(bytes = "vec", tag = "1")]
    pub flatbuffer: ::prost::alloc::vec::Vec<u8>,
}
include!("engine.tonic.rs");
// @@protoc_insertion_point(module)
