// Copyright Kamu Data, Inc. and contributors. All rights reserved.
//
// Use of this software is governed by the Business Source License
// included in the LICENSE file.
//
// As of the Change Date specified in that file, in accordance with
// the Business Source License, use of this software will be governed
// by the Apache License, Version 2.0.

use std::path::PathBuf;

use database_common::{DatabaseConnectionSettings, SqlitePlugin};
use sqlx::SqlitePool;

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

#[test_group::group(resourcegen)]
#[test_log::test(tokio::test)]
async fn dump_sqlite_schema() {
    let tmp = tempfile::tempdir().unwrap();
    let db_path = tmp.path().join("schema.sqlite.db");

    let base_catalog = dill::CatalogBuilder::new().build();
    let catalog = SqlitePlugin::catalog_with_connected_pool(
        &base_catalog,
        &DatabaseConnectionSettings::sqlite_from(&db_path),
    )
    .await
    .expect("Failed to initialize SQLite database");

    let pool = catalog.get_one::<SqlitePool>().unwrap();

    let rows: Vec<(String,)> =
        sqlx::query_as("SELECT sql FROM sqlite_master WHERE sql IS NOT NULL ORDER BY type, name")
            .fetch_all(pool.as_ref())
            .await
            .expect("Failed to query sqlite_master");

    let raw = rows
        .into_iter()
        .map(|(sql,)| sql)
        .collect::<Vec<_>>()
        .join(";\n\n");

    let schema_ddl = normalize_schema(&raw);

    let mut out_path = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    out_path.push("../../../../../resources/db/schema.sqlite.sql");

    std::fs::create_dir_all(out_path.parent().unwrap()).unwrap();
    std::fs::write(&out_path, build_output(&schema_ddl)).unwrap();
}

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

fn normalize_schema(ddl: &str) -> String {
    // sqlite_master stores DDL verbatim, but older and newer SQLite versions
    // differ in whether they store "CREATE TABLE IF NOT EXISTS" or "CREATE TABLE"
    // for the same migration SQL. Normalize to the plain form for stable output.
    ddl.replace("CREATE TABLE IF NOT EXISTS ", "CREATE TABLE ")
}

fn build_output(schema_ddl: &str) -> String {
    format!(
        "-- THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n--\n-- To regenerate \
         this file from existing migrations, use the following command:\n-- ```shell\n-- make \
         resources-db-schema\n-- ```\n\n{schema_ddl}"
    )
}

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
