CREATE OR REPLACE FUNCTION create_role_if_not_exists(rolename NAME, password TEXT) RETURNS TEXT AS
$$
BEGIN
    IF NOT EXISTS (SELECT * FROM pg_roles WHERE rolname = rolename) THEN
        EXECUTE format('CREATE ROLE %I WITH ENCRYPTED PASSWORD ''%I''', rolename, password);
        RETURN 'CREATE ROLE';
    ELSE
        RETURN format('ROLE ''%I'' ALREADY EXISTS', rolename);
    END IF;
END;
$$
LANGUAGE plpgsql;

SET vars.APP_DB_USERNAME = :APP_DB_USERNAME;
SET vars.APP_DB_PASSWORD = :APP_DB_PASSWORD;

SELECT create_role_if_not_exists(current_setting('vars.APP_DB_USERNAME'), current_setting('vars.APP_DB_PASSWORD'));

GRANT CONNECT ON DATABASE :DBNAME TO :APP_DB_USERNAME;
GRANT USAGE ON SCHEMA public TO :APP_DB_USERNAME;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public to :APP_DB_USERNAME;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public to :APP_DB_USERNAME;
