version: "3.8"

networks:
    kamu:

services:
    jupyter:
        image: ghcr.io/kamu-data/kamu-cli-demo-jupyter:0.18.0
        # Unfortunately running podman within another container requires elevated permissions
        privileged: true
        command:
            - "jupyter"
            - "notebook"
            - "--address=0.0.0.0"
            - "--port=8765"
            - "--NotebookApp.iopub_data_rate_limit=1000000000"
        environment:
            - AWS_ACCESS_KEY_ID=demo
            - AWS_SECRET_ACCESS_KEY=demo123
            # This is a free tier token - get one at https://etherscan.io/apis
            - ETHERSCAN_API_KEY=MST1914HGG228XNGTVQFJRE86QYJ3A52NA
            # TODO: Restore support for local RustFS
            - GITHUB_LOGIN=guest
            - GITHUB_TOKEN=
            - KAMU_NODE_URL=odf+https://node.demo.kamu.dev/
            - KAMU_WEB_UI_URL=https://platform.demo.kamu.dev/
        # volumes:
        #     - ./podman-images:/var/lib/containers/shared:ro
        #     - "./user-home/01 - Kamu Basics (COVID-19 example):/home/jovyan/01 - Kamu Basics (COVID-19 example)"
        #     - "./user-home/02 - Web3 Data (Ethereum trading example):/home/jovyan/02 - Web3 Data (Ethereum trading example)"
        #     - "./user-home/XX - Other Examples:/home/jovyan/XX - Other Examples"
        networks:
            - kamu
        ports:
            - "8765:8765"
        depends_on:
            - rustfs

    rustfs:
        image: ghcr.io/kamu-data/kamu-cli-demo-rustfs:0.18.0
        command:
            - "server"
            - "--address"
            - ":80"
            - "/data"
        environment:
            - RUSTFS_ACCESS_KEY=demo
            - RUSTFS_SECRET_KEY=demo123
        # volumes:
        #     - ./data:/data
        networks:
            - kamu
        expose:
            - "80"
        # ports:
        #     - "9000:9000"
