ARG IMAGE_SQLX_TAG
FROM ghcr.io/kamu-data/sqlx-cli:$IMAGE_SQLX_TAG

LABEL org.opencontainers.image.source https://github.com/kamu-data/kamu-cli

################################################################################

COPY ./migrations/ /migrations/
