-- THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
--
-- To regenerate this file from existing migrations, use the following command:
-- ```shell
-- make resources-db-schema
-- ```

--
-- PostgreSQL database dump
--



SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: account_type; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.account_type AS ENUM (
    'user',
    'organization'
);


--
-- Name: dataset_kind; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.dataset_kind AS ENUM (
    'root',
    'derivative'
);


--
-- Name: did_entity_type; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.did_entity_type AS ENUM (
    'account',
    'dataset'
);


--
-- Name: flow_process_auto_stop_reason; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.flow_process_auto_stop_reason AS ENUM (
    'stop_policy',
    'unrecoverable_failure'
);


--
-- Name: flow_process_effective_state; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.flow_process_effective_state AS ENUM (
    'stopped_auto',
    'failing',
    'unconfigured',
    'paused_manual',
    'active'
);


--
-- Name: flow_process_user_intent; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.flow_process_user_intent AS ENUM (
    'undefined',
    'enabled',
    'paused'
);


--
-- Name: flow_status_type; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.flow_status_type AS ENUM (
    'waiting',
    'running',
    'retrying',
    'finished'
);


--
-- Name: flow_stop_policy_kind; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.flow_stop_policy_kind AS ENUM (
    'never',
    'after_consecutive_failures'
);


--
-- Name: metadata_event_type; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.metadata_event_type AS ENUM (
    'AddData',
    'ExecuteTransform',
    'Seed',
    'SetPollingSource',
    'SetTransform',
    'SetVocab',
    'SetAttachments',
    'SetInfo',
    'SetLicense',
    'SetDataSchema',
    'AddPushSource',
    'DisablePushSource',
    'DisablePollingSource'
);


--
-- Name: rebac_entity_type; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.rebac_entity_type AS ENUM (
    'account',
    'dataset'
);


--
-- Name: task_status_type; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.task_status_type AS ENUM (
    'queued',
    'running',
    'finished'
);


--
-- Name: webhook_subscription_status; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.webhook_subscription_status AS ENUM (
    'UNVERIFIED',
    'ENABLED',
    'PAUSED',
    'UNREACHABLE',
    'REMOVED'
);


--
-- Name: create_app_user_role_if_not_exists(name, name, text); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.create_app_user_role_if_not_exists(db_name name, rolename name, role_password text) RETURNS text
    LANGUAGE plpgsql
    AS $$
BEGIN
    -- Check role is not present
    IF NOT EXISTS (SELECT * FROM pg_roles WHERE rolname = rolename) THEN
        -- Create role and grant basic access
        EXECUTE format('CREATE ROLE %I WITH LOGIN PASSWORD ''%s''', rolename, role_password);
        EXECUTE format('GRANT CONNECT ON DATABASE %I TO %I', db_name, rolename);
        EXECUTE format('GRANT USAGE ON SCHEMA public TO %I', rolename);
        -- Privileges for existing objects
        EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO %I', rolename);
        EXECUTE format('GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO %I', rolename);
        -- Default privileges (affects future objects)
        EXECUTE format('ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO %I', rolename);
        EXECUTE format('ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE ON SEQUENCES TO %I', rolename);
        RETURN format('CREATE ROLE %I', rolename);
    ELSE
        -- Role already exists
        RETURN format('ROLE ''%I'' ALREADY EXISTS', rolename);
    END IF;
END;
$$;


--
-- Name: notify_flow_activation_scheduled(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.notify_flow_activation_scheduled() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    PERFORM pg_notify('flow_activation_scheduled', '');
    RETURN NULL;
END $$;


--
-- Name: notify_flow_system_events(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.notify_flow_system_events() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    PERFORM pg_notify('flow_system_events_ready', '');
    RETURN NULL;
END $$;


--
-- Name: notify_outbox_messages(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.notify_outbox_messages() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    PERFORM pg_notify('outbox_messages_ready', '');
    RETURN NULL;
END $$;


--
-- Name: notify_tasks_queued(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.notify_tasks_queued() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    PERFORM pg_notify('tasks_queued', '');
    RETURN NULL;
END $$;


--
-- Name: trg_embeddings_cache_check_dims(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.trg_embeddings_cache_check_dims() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE
    expected INT;
    actual   INT;
BEGIN
    SELECT dims INTO expected
    FROM embedding_models
    WHERE id = new.model_id;

    IF expected IS NULL THEN
        RAISE EXCEPTION 'Unknown model_id %', new.model_id;
    END IF;

    IF octet_length(new.embedding) <> expected * 4 THEN
        raise exception 'Embedding dims mismatch: expected % bytes, got %',
        expected * 4, octet_length(new.embedding);
    END IF;

    RETURN new;
END;
$$;


--
-- Name: wipe_outbox_data(); Type: PROCEDURE; Schema: public; Owner: -
--

CREATE PROCEDURE public.wipe_outbox_data()
    LANGUAGE plpgsql
    AS $$
BEGIN
    -- Truncate tables
    TRUNCATE TABLE outbox_message_consumptions;
    TRUNCATE TABLE outbox_messages;

    -- Explicitly reset the sequence
    PERFORM setval('outbox_message_id_seq', 1, false);
END;
$$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: _sqlx_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public._sqlx_migrations (
    version bigint NOT NULL,
    description text NOT NULL,
    installed_on timestamp with time zone DEFAULT now() NOT NULL,
    success boolean NOT NULL,
    checksum bytea NOT NULL,
    execution_time bigint NOT NULL
);


--
-- Name: access_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.access_tokens (
    id uuid NOT NULL,
    token_name character varying(100) NOT NULL,
    token_hash bytea NOT NULL,
    created_at timestamp with time zone NOT NULL,
    revoked_at timestamp with time zone,
    last_used_at timestamp with time zone,
    account_id character varying(100) NOT NULL
);


--
-- Name: account_quota_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.account_quota_events (
    id bigint NOT NULL,
    account_id text NOT NULL,
    quota_type text NOT NULL,
    event_type text NOT NULL,
    event_payload jsonb NOT NULL,
    event_time timestamp with time zone DEFAULT now() NOT NULL,
    prev_event_id bigint
);


--
-- Name: account_quota_events_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.account_quota_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: account_quota_events_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.account_quota_events_id_seq OWNED BY public.account_quota_events.id;


--
-- Name: accounts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.accounts (
    id character varying(100) NOT NULL,
    account_name character varying(100) NOT NULL,
    email character varying(320) NOT NULL,
    display_name character varying(200) NOT NULL,
    account_type public.account_type NOT NULL,
    avatar_url character varying(1000),
    registered_at timestamp with time zone NOT NULL,
    provider character varying(25) NOT NULL,
    provider_identity_key character varying(100) NOT NULL,
    resource_id uuid NOT NULL
);


--
-- Name: accounts_passwords; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.accounts_passwords (
    password_hash character varying(100) NOT NULL,
    account_id character varying(100) NOT NULL
);


--
-- Name: auth_rebac_properties; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_rebac_properties (
    entity_type public.rebac_entity_type NOT NULL,
    entity_id character varying(100) NOT NULL,
    property_name character varying(50) NOT NULL,
    property_value character varying(50) NOT NULL
);


--
-- Name: auth_rebac_relations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_rebac_relations (
    subject_entity_type public.rebac_entity_type NOT NULL,
    subject_entity_id character varying(100) NOT NULL,
    relationship character varying(50) NOT NULL,
    object_entity_type public.rebac_entity_type NOT NULL,
    object_entity_id character varying(100) NOT NULL
);


--
-- Name: config_secret_set_entries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.config_secret_set_entries (
    entry_id uuid NOT NULL,
    resource_id uuid NOT NULL,
    resource_generation bigint NOT NULL,
    account_id character varying(100) NOT NULL,
    secret_key character varying(200) NOT NULL,
    value bytea NOT NULL,
    secret_nonce bytea NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


--
-- Name: config_variable_set_entries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.config_variable_set_entries (
    entry_id uuid NOT NULL,
    resource_id uuid NOT NULL,
    resource_generation bigint NOT NULL,
    account_id character varying(100) NOT NULL,
    variable_key character varying(200) NOT NULL,
    value text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


--
-- Name: dataset_data_blocks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dataset_data_blocks (
    dataset_id character varying(100) NOT NULL,
    block_ref_name character varying(50) NOT NULL,
    event_type public.metadata_event_type NOT NULL,
    sequence_number bigint NOT NULL,
    block_hash_bin bytea NOT NULL,
    block_hash_hex text GENERATED ALWAYS AS (('f1620'::text || encode(block_hash_bin, 'hex'::text))) STORED,
    block_payload bytea NOT NULL,
    CONSTRAINT dataset_data_blocks_event_type_check CHECK (((event_type = 'AddData'::public.metadata_event_type) OR (event_type = 'ExecuteTransform'::public.metadata_event_type)))
);


--
-- Name: dataset_dependencies; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dataset_dependencies (
    upstream_dataset_id character varying(100) NOT NULL,
    downstream_dataset_id character varying(100) NOT NULL
);


--
-- Name: dataset_entries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dataset_entries (
    dataset_id character varying(100) NOT NULL,
    owner_id character varying(100) NOT NULL,
    dataset_name character varying(100) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    kind public.dataset_kind NOT NULL,
    owner_name character varying(100) NOT NULL
);


--
-- Name: dataset_key_blocks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dataset_key_blocks (
    dataset_id character varying(100) NOT NULL,
    block_ref_name character varying(50) NOT NULL,
    event_type public.metadata_event_type NOT NULL,
    sequence_number bigint NOT NULL,
    block_hash_bin bytea NOT NULL,
    block_hash_hex text GENERATED ALWAYS AS (('f1620'::text || encode(block_hash_bin, 'hex'::text))) STORED,
    block_payload bytea NOT NULL,
    CONSTRAINT dataset_key_blocks_event_type_check CHECK (((event_type <> 'AddData'::public.metadata_event_type) AND (event_type <> 'ExecuteTransform'::public.metadata_event_type)))
);


--
-- Name: dataset_references; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dataset_references (
    dataset_id character varying(100) NOT NULL,
    block_ref_name character varying(50) NOT NULL,
    block_hash_bin bytea NOT NULL,
    block_hash_hex text GENERATED ALWAYS AS (('f1620'::text || encode(block_hash_bin, 'hex'::text))) STORED
);


--
-- Name: dataset_statistics; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dataset_statistics (
    dataset_id character varying(100) NOT NULL,
    block_ref_name character varying(50) NOT NULL,
    last_pulled timestamp with time zone,
    num_records bigint NOT NULL,
    data_size bigint NOT NULL,
    checkpoints_size bigint NOT NULL,
    num_object_links bigint DEFAULT 0 NOT NULL,
    object_links_size bigint DEFAULT 0 NOT NULL
);


--
-- Name: did_secret_keys; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.did_secret_keys (
    entity_type public.did_entity_type NOT NULL,
    entity_id character varying(100) NOT NULL,
    secret_nonce bytea NOT NULL,
    secret_key bytea NOT NULL
);


--
-- Name: embedding_models; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.embedding_models (
    id bigint NOT NULL,
    provider text NOT NULL,
    name text NOT NULL,
    revision text,
    dims integer NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: embedding_models_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.embedding_models_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: embedding_models_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.embedding_models_id_seq OWNED BY public.embedding_models.id;


--
-- Name: embeddings_cache; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.embeddings_cache (
    model_id bigint NOT NULL,
    input_hash bytea NOT NULL,
    input_text text NOT NULL,
    embedding bytea NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    last_seen_at timestamp with time zone DEFAULT now() NOT NULL,
    hit_count bigint DEFAULT 0 NOT NULL
);


--
-- Name: flow_system_event_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.flow_system_event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: flow_configuration_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.flow_configuration_events (
    event_id bigint DEFAULT nextval('public.flow_system_event_id_seq'::regclass) NOT NULL,
    event_type character varying(50) NOT NULL,
    event_time timestamp with time zone NOT NULL,
    event_payload jsonb NOT NULL,
    flow_type character varying(100) NOT NULL,
    scope_data jsonb NOT NULL,
    tx_id xid8 DEFAULT pg_current_xact_id() NOT NULL,
    prev_event_id bigint
);


--
-- Name: flow_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.flow_events (
    event_id bigint DEFAULT nextval('public.flow_system_event_id_seq'::regclass) NOT NULL,
    flow_id bigint NOT NULL,
    event_type character varying(50) NOT NULL,
    event_time timestamp with time zone NOT NULL,
    event_payload jsonb NOT NULL,
    tx_id xid8 DEFAULT pg_current_xact_id() NOT NULL
);


--
-- Name: flow_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.flow_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: flow_process_states; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.flow_process_states (
    scope_data jsonb NOT NULL,
    flow_type character varying(100) NOT NULL,
    user_intent public.flow_process_user_intent DEFAULT 'undefined'::public.flow_process_user_intent NOT NULL,
    stop_policy_kind public.flow_stop_policy_kind DEFAULT 'never'::public.flow_stop_policy_kind NOT NULL,
    stop_policy_data jsonb,
    consecutive_failures integer DEFAULT 0 NOT NULL,
    auto_stopped_reason public.flow_process_auto_stop_reason,
    last_success_at timestamp with time zone,
    last_failure_at timestamp with time zone,
    last_attempt_at timestamp with time zone,
    next_planned_at timestamp with time zone,
    auto_stopped_at timestamp with time zone,
    effective_state public.flow_process_effective_state NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    last_applied_flow_system_event_id bigint DEFAULT 0 NOT NULL,
    paused_at timestamp with time zone,
    running_since timestamp with time zone
);


--
-- Name: flow_trigger_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.flow_trigger_events (
    event_id bigint DEFAULT nextval('public.flow_system_event_id_seq'::regclass) NOT NULL,
    event_type character varying(50) NOT NULL,
    event_time timestamp with time zone NOT NULL,
    event_payload jsonb NOT NULL,
    flow_type character varying(100) NOT NULL,
    scope_data jsonb NOT NULL,
    tx_id xid8 DEFAULT pg_current_xact_id() NOT NULL,
    prev_event_id bigint
);


--
-- Name: flow_system_events; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public.flow_system_events AS
 SELECT flow_configuration_events.event_id,
    flow_configuration_events.tx_id,
    'configurations'::text AS source_stream,
    flow_configuration_events.event_type,
    flow_configuration_events.event_time,
    flow_configuration_events.event_payload
   FROM public.flow_configuration_events
UNION ALL
 SELECT flow_trigger_events.event_id,
    flow_trigger_events.tx_id,
    'triggers'::text AS source_stream,
    flow_trigger_events.event_type,
    flow_trigger_events.event_time,
    flow_trigger_events.event_payload
   FROM public.flow_trigger_events
UNION ALL
 SELECT flow_events.event_id,
    flow_events.tx_id,
    'flows'::text AS source_stream,
    flow_events.event_type,
    flow_events.event_time,
    flow_events.event_payload
   FROM public.flow_events;


--
-- Name: flow_system_projected_offsets; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.flow_system_projected_offsets (
    projector text NOT NULL,
    last_tx_id xid8 DEFAULT '0'::xid8 NOT NULL,
    last_event_id bigint DEFAULT 0 NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: flows; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.flows (
    flow_id bigint NOT NULL,
    initiator character varying(100) NOT NULL,
    flow_status public.flow_status_type NOT NULL,
    last_event_id bigint,
    scheduled_for_activation_at timestamp with time zone,
    flow_type character varying(100) NOT NULL,
    scope_data jsonb NOT NULL
);


--
-- Name: oauth_device_codes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.oauth_device_codes (
    device_code uuid NOT NULL,
    device_code_created_at timestamp with time zone NOT NULL,
    device_code_expires_at timestamp with time zone NOT NULL,
    token_iat bigint,
    token_exp bigint,
    token_last_used_at timestamp with time zone,
    account_id character varying(100)
);


--
-- Name: outbox_message_consumptions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.outbox_message_consumptions (
    consumer_name character varying(200) NOT NULL,
    producer_name character varying(200) NOT NULL,
    last_consumed_message_id bigint NOT NULL,
    last_tx_id xid8 DEFAULT '0'::xid8 NOT NULL
);


--
-- Name: outbox_message_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.outbox_message_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: outbox_messages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.outbox_messages (
    message_id bigint DEFAULT nextval('public.outbox_message_id_seq'::regclass) NOT NULL,
    producer_name character varying(200) NOT NULL,
    content_json jsonb NOT NULL,
    occurred_on timestamp with time zone NOT NULL,
    version integer,
    tx_id xid8 DEFAULT pg_current_xact_id() NOT NULL
);


--
-- Name: resource_event_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.resource_event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: resource_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.resource_events (
    event_id bigint DEFAULT nextval('public.resource_event_id_seq'::regclass) NOT NULL,
    resource_id uuid NOT NULL,
    resource_schema text NOT NULL,
    event_time timestamp with time zone NOT NULL,
    event_type character varying(100) NOT NULL,
    event_payload jsonb NOT NULL
);


--
-- Name: resource_labels_projection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.resource_labels_projection (
    resource_id uuid NOT NULL,
    label_key text NOT NULL,
    label_value text NOT NULL
);


--
-- Name: resources; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.resources (
    resource_id uuid NOT NULL,
    account_id character varying(100) NOT NULL,
    resource_schema text NOT NULL,
    resource_name character varying(200) NOT NULL,
    labels jsonb NOT NULL,
    annotations jsonb NOT NULL,
    spec jsonb NOT NULL,
    status jsonb,
    generation bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    last_event_id bigint
);


--
-- Name: task_event_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.task_event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: task_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.task_events (
    event_id bigint DEFAULT nextval('public.task_event_id_seq'::regclass) NOT NULL,
    task_id bigint NOT NULL,
    event_time timestamp with time zone NOT NULL,
    event_type character varying(50) NOT NULL,
    event_payload jsonb NOT NULL
);


--
-- Name: task_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.task_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: tasks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tasks (
    task_id bigint NOT NULL,
    dataset_id character varying(100),
    task_status public.task_status_type NOT NULL,
    last_event_id bigint
);


--
-- Name: web3_auth_eip4361_nonces; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.web3_auth_eip4361_nonces (
    wallet_address character varying(100) NOT NULL,
    nonce character varying(32) NOT NULL,
    expires_at timestamp with time zone NOT NULL
);


--
-- Name: webhook_deliveries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.webhook_deliveries (
    delivery_id uuid CONSTRAINT webhook_deliveries_new_delivery_id_not_null NOT NULL,
    subscription_id uuid CONSTRAINT webhook_deliveries_new_subscription_id_not_null NOT NULL,
    event_type character varying(64) CONSTRAINT webhook_deliveries_new_event_type_not_null NOT NULL,
    request_payload jsonb CONSTRAINT webhook_deliveries_new_request_payload_not_null NOT NULL,
    request_headers jsonb CONSTRAINT webhook_deliveries_new_request_headers_not_null NOT NULL,
    requested_at timestamp with time zone CONSTRAINT webhook_deliveries_new_requested_at_not_null NOT NULL,
    response_code smallint,
    response_body text,
    response_headers jsonb,
    response_at timestamp with time zone
);


--
-- Name: webhook_subscription_event_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.webhook_subscription_event_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: webhook_subscription_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.webhook_subscription_events (
    event_id bigint DEFAULT nextval('public.webhook_subscription_event_seq'::regclass) NOT NULL,
    subscription_id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    event_type character varying(50) NOT NULL,
    event_payload jsonb NOT NULL
);


--
-- Name: webhook_subscriptions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.webhook_subscriptions (
    id uuid NOT NULL,
    dataset_id character varying(100),
    event_types character varying(64)[] NOT NULL,
    status public.webhook_subscription_status DEFAULT 'UNVERIFIED'::public.webhook_subscription_status NOT NULL,
    label character varying(100),
    last_event_id bigint
);


--
-- Name: account_quota_events id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account_quota_events ALTER COLUMN id SET DEFAULT nextval('public.account_quota_events_id_seq'::regclass);


--
-- Name: embedding_models id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.embedding_models ALTER COLUMN id SET DEFAULT nextval('public.embedding_models_id_seq'::regclass);


--
-- Name: _sqlx_migrations _sqlx_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public._sqlx_migrations
    ADD CONSTRAINT _sqlx_migrations_pkey PRIMARY KEY (version);


--
-- Name: access_tokens access_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.access_tokens
    ADD CONSTRAINT access_tokens_pkey PRIMARY KEY (id);


--
-- Name: account_quota_events account_quota_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account_quota_events
    ADD CONSTRAINT account_quota_events_pkey PRIMARY KEY (id);


--
-- Name: accounts accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_pkey PRIMARY KEY (id);


--
-- Name: dataset_data_blocks dataset_data_blocks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dataset_data_blocks
    ADD CONSTRAINT dataset_data_blocks_pkey PRIMARY KEY (dataset_id, block_ref_name, sequence_number);


--
-- Name: dataset_entries dataset_entries_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dataset_entries
    ADD CONSTRAINT dataset_entries_pkey PRIMARY KEY (dataset_id);


--
-- Name: dataset_key_blocks dataset_key_blocks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dataset_key_blocks
    ADD CONSTRAINT dataset_key_blocks_pkey PRIMARY KEY (dataset_id, block_ref_name, sequence_number);


--
-- Name: embedding_models embedding_models_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.embedding_models
    ADD CONSTRAINT embedding_models_pkey PRIMARY KEY (id);


--
-- Name: embeddings_cache embeddings_cache_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.embeddings_cache
    ADD CONSTRAINT embeddings_cache_pkey PRIMARY KEY (model_id, input_hash);


--
-- Name: flow_configuration_events flow_configuration_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.flow_configuration_events
    ADD CONSTRAINT flow_configuration_events_pkey PRIMARY KEY (event_id);


--
-- Name: flow_events flow_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.flow_events
    ADD CONSTRAINT flow_events_pkey PRIMARY KEY (event_id);


--
-- Name: flow_process_states flow_process_state_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.flow_process_states
    ADD CONSTRAINT flow_process_state_pkey PRIMARY KEY (scope_data, flow_type);


--
-- Name: flow_system_projected_offsets flow_system_projected_offsets_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.flow_system_projected_offsets
    ADD CONSTRAINT flow_system_projected_offsets_pkey PRIMARY KEY (projector);


--
-- Name: flow_trigger_events flow_trigger_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.flow_trigger_events
    ADD CONSTRAINT flow_trigger_events_pkey PRIMARY KEY (event_id);


--
-- Name: flows flows_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.flows
    ADD CONSTRAINT flows_pkey PRIMARY KEY (flow_id);


--
-- Name: oauth_device_codes oauth_device_codes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.oauth_device_codes
    ADD CONSTRAINT oauth_device_codes_pkey PRIMARY KEY (device_code);


--
-- Name: outbox_message_consumptions outbox_message_consumptions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.outbox_message_consumptions
    ADD CONSTRAINT outbox_message_consumptions_pkey PRIMARY KEY (consumer_name, producer_name);


--
-- Name: outbox_messages outbox_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.outbox_messages
    ADD CONSTRAINT outbox_messages_pkey PRIMARY KEY (message_id);


--
-- Name: resource_events resource_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resource_events
    ADD CONSTRAINT resource_events_pkey PRIMARY KEY (event_id);


--
-- Name: resource_labels_projection resource_labels_projection_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resource_labels_projection
    ADD CONSTRAINT resource_labels_projection_pkey PRIMARY KEY (resource_id, label_key);


--
-- Name: resources resources_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resources
    ADD CONSTRAINT resources_pkey PRIMARY KEY (resource_id);


--
-- Name: task_events task_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.task_events
    ADD CONSTRAINT task_events_pkey PRIMARY KEY (event_id);


--
-- Name: tasks tasks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tasks
    ADD CONSTRAINT tasks_pkey PRIMARY KEY (task_id);


--
-- Name: config_secret_set_entries uq_config_secret_set_entries_resource_generation_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.config_secret_set_entries
    ADD CONSTRAINT uq_config_secret_set_entries_resource_generation_key UNIQUE (resource_id, resource_generation, secret_key);


--
-- Name: config_variable_set_entries uq_config_variable_set_entries_resource_generation_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.config_variable_set_entries
    ADD CONSTRAINT uq_config_variable_set_entries_resource_generation_key UNIQUE (resource_id, resource_generation, variable_key);


--
-- Name: web3_auth_eip4361_nonces web3_auth_eip4361_nonces_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.web3_auth_eip4361_nonces
    ADD CONSTRAINT web3_auth_eip4361_nonces_pkey PRIMARY KEY (wallet_address);


--
-- Name: webhook_deliveries webhook_deliveries_new_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.webhook_deliveries
    ADD CONSTRAINT webhook_deliveries_new_pkey PRIMARY KEY (delivery_id);


--
-- Name: webhook_subscription_events webhook_subscription_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.webhook_subscription_events
    ADD CONSTRAINT webhook_subscription_events_pkey PRIMARY KEY (event_id);


--
-- Name: webhook_subscriptions webhook_subscriptions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.webhook_subscriptions
    ADD CONSTRAINT webhook_subscriptions_pkey PRIMARY KEY (id);


--
-- Name: embedding_models_unique_key; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX embedding_models_unique_key ON public.embedding_models USING btree (provider, name, COALESCE(revision, ''::text));


--
-- Name: embeddings_cache_last_seen_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX embeddings_cache_last_seen_idx ON public.embeddings_cache USING btree (last_seen_at);


--
-- Name: idx_access_tokens_account_id_token_name; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_access_tokens_account_id_token_name ON public.access_tokens USING btree (account_id, token_name) WHERE (revoked_at IS NULL);


--
-- Name: idx_account_quota_events_account_type; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_account_quota_events_account_type ON public.account_quota_events USING btree (account_id, quota_type);


--
-- Name: idx_account_quota_events_account_type_prev_event; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_account_quota_events_account_type_prev_event ON public.account_quota_events USING btree (account_id, quota_type, prev_event_id) WHERE (prev_event_id IS NOT NULL);


--
-- Name: idx_account_quota_events_event_time; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_account_quota_events_event_time ON public.account_quota_events USING btree (event_time);


--
-- Name: idx_accounts_email; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_accounts_email ON public.accounts USING btree (lower((email)::text));


--
-- Name: idx_accounts_name; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_accounts_name ON public.accounts USING btree (lower((account_name)::text));


--
-- Name: idx_accounts_resource_id; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_accounts_resource_id ON public.accounts USING btree (resource_id);


--
-- Name: idx_auth_did_secret_keys; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_auth_did_secret_keys ON public.did_secret_keys USING btree (entity_type, entity_id);


--
-- Name: idx_auth_did_secret_keys_unique_entity_id; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_auth_did_secret_keys_unique_entity_id ON public.did_secret_keys USING btree (entity_id);


--
-- Name: idx_auth_rebac_properties_entity; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_auth_rebac_properties_entity ON public.auth_rebac_properties USING btree (entity_type, entity_id);


--
-- Name: idx_auth_rebac_properties_entity_property_name; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_auth_rebac_properties_entity_property_name ON public.auth_rebac_properties USING btree (entity_type, entity_id, property_name);


--
-- Name: idx_auth_rebac_relations_object_entity; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_auth_rebac_relations_object_entity ON public.auth_rebac_relations USING btree (object_entity_type, object_entity_id);


--
-- Name: idx_auth_rebac_relations_row; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_auth_rebac_relations_row ON public.auth_rebac_relations USING btree (subject_entity_type, subject_entity_id, object_entity_type, object_entity_id);


--
-- Name: idx_auth_rebac_relations_subject_entity; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_auth_rebac_relations_subject_entity ON public.auth_rebac_relations USING btree (subject_entity_type, subject_entity_id);


--
-- Name: idx_config_secret_set_entries_account_key; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_config_secret_set_entries_account_key ON public.config_secret_set_entries USING btree (account_id, secret_key);


--
-- Name: idx_config_secret_set_entries_resource_id_generation; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_config_secret_set_entries_resource_id_generation ON public.config_secret_set_entries USING btree (resource_id, resource_generation);


--
-- Name: idx_config_variable_set_entries_account_key; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_config_variable_set_entries_account_key ON public.config_variable_set_entries USING btree (account_id, variable_key);


--
-- Name: idx_config_variable_set_entries_resource_id_generation; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_config_variable_set_entries_resource_id_generation ON public.config_variable_set_entries USING btree (resource_id, resource_generation);


--
-- Name: idx_dataset_data_blocks_by_hash; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_dataset_data_blocks_by_hash ON public.dataset_data_blocks USING btree (dataset_id, block_hash_bin);


--
-- Name: idx_dataset_data_blocks_latest_event; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_dataset_data_blocks_latest_event ON public.dataset_data_blocks USING btree (dataset_id, block_ref_name, event_type, sequence_number DESC);


--
-- Name: idx_dataset_dependencies; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_dataset_dependencies ON public.dataset_dependencies USING btree (upstream_dataset_id, downstream_dataset_id);


--
-- Name: idx_dataset_dependencies_downstream_dataset_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_dataset_dependencies_downstream_dataset_id ON public.dataset_dependencies USING btree (downstream_dataset_id);


--
-- Name: idx_dataset_dependencies_upstream_dataset_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_dataset_dependencies_upstream_dataset_id ON public.dataset_dependencies USING btree (upstream_dataset_id);


--
-- Name: idx_dataset_entries_owner_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_dataset_entries_owner_id ON public.dataset_entries USING btree (owner_id);


--
-- Name: idx_dataset_entries_owner_id_dataset_name; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_dataset_entries_owner_id_dataset_name ON public.dataset_entries USING btree (owner_id, lower((dataset_name)::text));


--
-- Name: idx_dataset_key_blocks_by_hash; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_dataset_key_blocks_by_hash ON public.dataset_key_blocks USING btree (dataset_id, block_hash_bin);


--
-- Name: idx_dataset_key_blocks_latest_event; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_dataset_key_blocks_latest_event ON public.dataset_key_blocks USING btree (dataset_id, block_ref_name, event_type, sequence_number DESC);


--
-- Name: idx_dataset_references; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_dataset_references ON public.dataset_references USING btree (dataset_id, block_ref_name);


--
-- Name: idx_dataset_statistics; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_dataset_statistics ON public.dataset_statistics USING btree (dataset_id, block_ref_name);


--
-- Name: idx_fce_latest_per_scope; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_fce_latest_per_scope ON public.flow_configuration_events USING btree (flow_type, scope_data, event_time DESC);


--
-- Name: idx_fce_scope_data_hash; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_fce_scope_data_hash ON public.flow_configuration_events USING hash (scope_data);


--
-- Name: idx_fce_tx_order; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_fce_tx_order ON public.flow_configuration_events USING btree (tx_id, event_id);


--
-- Name: idx_fe_flow_id_event_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_fe_flow_id_event_id ON public.flow_events USING btree (flow_id, event_id);


--
-- Name: idx_fe_tx_order; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_fe_tx_order ON public.flow_events USING btree (tx_id, event_id);


--
-- Name: idx_flow_configuration_events_binding_prev_event; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_flow_configuration_events_binding_prev_event ON public.flow_configuration_events USING btree (flow_type, scope_data, prev_event_id) WHERE (prev_event_id IS NOT NULL);


--
-- Name: idx_flow_trigger_events_binding_prev_event; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_flow_trigger_events_binding_prev_event ON public.flow_trigger_events USING btree (flow_type, scope_data, prev_event_id) WHERE (prev_event_id IS NOT NULL);


--
-- Name: idx_flows_active_scope_last; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_flows_active_scope_last ON public.flows USING btree (scope_data, flow_type, flow_id DESC) WHERE (flow_status <> 'finished'::public.flow_status_type);


--
-- Name: idx_flows_initiator_nonsystem; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_flows_initiator_nonsystem ON public.flows USING btree (initiator) WHERE ((initiator)::text <> '<system>'::text);


--
-- Name: idx_flows_ready_by_time; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_flows_ready_by_time ON public.flows USING btree (scheduled_for_activation_at, flow_id) WHERE ((scheduled_for_activation_at IS NOT NULL) AND (flow_status = ANY (ARRAY['waiting'::public.flow_status_type, 'retrying'::public.flow_status_type])));


--
-- Name: idx_flows_scope_data_hash; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_flows_scope_data_hash ON public.flows USING hash (scope_data);


--
-- Name: idx_flows_scope_dataset; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_flows_scope_dataset ON public.flows USING btree (((scope_data ->> 'dataset_id'::text)));


--
-- Name: idx_flows_scope_subscription_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_flows_scope_subscription_id ON public.flows USING btree (((scope_data ->> 'subscription_id'::text)));


--
-- Name: idx_flows_scope_type; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_flows_scope_type ON public.flows USING btree (((scope_data ->> 'type'::text)));


--
-- Name: idx_flows_status_last_event; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_flows_status_last_event ON public.flows USING btree (flow_status, last_event_id DESC, flow_id DESC);


--
-- Name: idx_fps_dataset_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_fps_dataset_id ON public.flow_process_states USING btree (((scope_data ->> 'dataset_id'::text)));


--
-- Name: idx_fps_dataset_only; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_fps_dataset_only ON public.flow_process_states USING btree (((scope_data ->> 'dataset_id'::text))) WHERE ((scope_data ->> 'type'::text) = 'Dataset'::text);


--
-- Name: idx_fps_effective_state; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_fps_effective_state ON public.flow_process_states USING btree (effective_state);


--
-- Name: idx_fps_last_attempt_desc; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_fps_last_attempt_desc ON public.flow_process_states USING btree (last_attempt_at DESC);


--
-- Name: idx_fps_last_failure_desc; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_fps_last_failure_desc ON public.flow_process_states USING btree (last_failure_at DESC);


--
-- Name: idx_fps_updates_next; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_fps_updates_next ON public.flow_process_states USING btree (next_planned_at) WHERE ((flow_type)::text = ANY ((ARRAY['dev.kamu.flow.dataset.ingest'::character varying, 'dev.kamu.flow.dataset.transform'::character varying])::text[]));


--
-- Name: idx_fps_webhook_only; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_fps_webhook_only ON public.flow_process_states USING btree (((scope_data ->> 'dataset_id'::text))) WHERE ((scope_data ->> 'type'::text) = 'WebhookSubscription'::text);


--
-- Name: idx_fte_latest_per_scope; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_fte_latest_per_scope ON public.flow_trigger_events USING btree (flow_type, scope_data, event_time DESC);


--
-- Name: idx_fte_scope_data_hash; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_fte_scope_data_hash ON public.flow_trigger_events USING hash (scope_data);


--
-- Name: idx_fte_tx_order; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_fte_tx_order ON public.flow_trigger_events USING btree (tx_id, event_id);


--
-- Name: idx_oauth_device_codes_device_code_expires_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_oauth_device_codes_device_code_expires_at ON public.oauth_device_codes USING btree (device_code_expires_at DESC);


--
-- Name: idx_om_tx_order; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_om_tx_order ON public.outbox_messages USING btree (tx_id, message_id);


--
-- Name: idx_outbox_messages_producer_name; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_outbox_messages_producer_name ON public.outbox_messages USING btree (producer_name);


--
-- Name: idx_resource_events_resource_id_event_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_resource_events_resource_id_event_id ON public.resource_events USING btree (resource_id, event_id);


--
-- Name: idx_resource_events_schema_event_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_resource_events_schema_event_id ON public.resource_events USING btree (resource_schema, event_id);


--
-- Name: idx_resource_labels_projection_key_value_resource_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_resource_labels_projection_key_value_resource_id ON public.resource_labels_projection USING btree (label_key, label_value, resource_id);


--
-- Name: idx_resources_account_schema_name_ci; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_resources_account_schema_name_ci ON public.resources USING btree (account_id, resource_schema, lower((resource_name)::text));


--
-- Name: idx_resources_account_schema_updated_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_resources_account_schema_updated_at ON public.resources USING btree (account_id, resource_schema, updated_at DESC);


--
-- Name: idx_resources_summary_projection; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_resources_summary_projection ON public.resources USING btree (account_id, resource_schema, ((status ->> 'phase'::text))) WHERE (deleted_at IS NULL);


--
-- Name: idx_task_events_task_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_task_events_task_id ON public.task_events USING btree (task_id);


--
-- Name: idx_tasks_dataset_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tasks_dataset_id ON public.tasks USING btree (dataset_id) WHERE (dataset_id IS NOT NULL);


--
-- Name: idx_tasks_task_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tasks_task_status ON public.tasks USING btree (task_status) WHERE (task_status <> 'finished'::public.task_status_type);


--
-- Name: idx_uniq_accounts_provider_provider_identity_key; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_uniq_accounts_provider_provider_identity_key ON public.accounts USING btree (provider, provider_identity_key);


--
-- Name: idx_webhook_deliveries_subscription_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_webhook_deliveries_subscription_id ON public.webhook_deliveries USING btree (subscription_id);


--
-- Name: idx_webhook_subscription_dataset_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_webhook_subscription_dataset_status ON public.webhook_subscriptions USING btree (dataset_id, status) WHERE (dataset_id IS NOT NULL);


--
-- Name: idx_webhook_subscription_events_subscription_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_webhook_subscription_events_subscription_id ON public.webhook_subscription_events USING btree (subscription_id);


--
-- Name: uniq_webhook_subscription_label; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uniq_webhook_subscription_label ON public.webhook_subscriptions USING btree (dataset_id, label) WHERE ((label IS NOT NULL) AND (status <> 'REMOVED'::public.webhook_subscription_status));


--
-- Name: embeddings_cache embeddings_cache_check_dims; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER embeddings_cache_check_dims BEFORE INSERT OR UPDATE OF model_id, embedding ON public.embeddings_cache FOR EACH ROW EXECUTE FUNCTION public.trg_embeddings_cache_check_dims();


--
-- Name: flow_configuration_events fce_notify; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER fce_notify AFTER INSERT ON public.flow_configuration_events REFERENCING NEW TABLE AS new_rows FOR EACH STATEMENT EXECUTE FUNCTION public.notify_flow_system_events();


--
-- Name: flow_events fe_notify; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER fe_notify AFTER INSERT ON public.flow_events REFERENCING NEW TABLE AS new_rows FOR EACH STATEMENT EXECUTE FUNCTION public.notify_flow_system_events();


--
-- Name: flows flows_activation_notify; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER flows_activation_notify AFTER UPDATE OF scheduled_for_activation_at ON public.flows FOR EACH ROW WHEN (((new.scheduled_for_activation_at IS NOT NULL) AND (new.scheduled_for_activation_at IS DISTINCT FROM old.scheduled_for_activation_at))) EXECUTE FUNCTION public.notify_flow_activation_scheduled();


--
-- Name: flow_trigger_events fte_notify; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER fte_notify AFTER INSERT ON public.flow_trigger_events REFERENCING NEW TABLE AS new_rows FOR EACH STATEMENT EXECUTE FUNCTION public.notify_flow_system_events();


--
-- Name: outbox_messages outbox_notify; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER outbox_notify AFTER INSERT ON public.outbox_messages REFERENCING NEW TABLE AS new_rows FOR EACH STATEMENT EXECUTE FUNCTION public.notify_outbox_messages();


--
-- Name: tasks tasks_insert_notify; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER tasks_insert_notify AFTER INSERT ON public.tasks FOR EACH STATEMENT EXECUTE FUNCTION public.notify_tasks_queued();


--
-- Name: tasks tasks_requeue_notify; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER tasks_requeue_notify AFTER UPDATE OF task_status ON public.tasks FOR EACH ROW WHEN (((new.task_status = 'queued'::public.task_status_type) AND (old.task_status IS DISTINCT FROM new.task_status))) EXECUTE FUNCTION public.notify_tasks_queued();


--
-- Name: dataset_data_blocks dataset_data_blocks_dataset_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dataset_data_blocks
    ADD CONSTRAINT dataset_data_blocks_dataset_id_fkey FOREIGN KEY (dataset_id) REFERENCES public.dataset_entries(dataset_id) ON DELETE CASCADE;


--
-- Name: dataset_key_blocks dataset_key_blocks_dataset_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dataset_key_blocks
    ADD CONSTRAINT dataset_key_blocks_dataset_id_fkey FOREIGN KEY (dataset_id) REFERENCES public.dataset_entries(dataset_id) ON DELETE CASCADE;


--
-- Name: dataset_references dataset_references_dataset_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dataset_references
    ADD CONSTRAINT dataset_references_dataset_id_fkey FOREIGN KEY (dataset_id) REFERENCES public.dataset_entries(dataset_id) ON DELETE CASCADE;


--
-- Name: dataset_statistics dataset_statistics_dataset_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dataset_statistics
    ADD CONSTRAINT dataset_statistics_dataset_id_fkey FOREIGN KEY (dataset_id) REFERENCES public.dataset_entries(dataset_id) ON DELETE CASCADE;


--
-- Name: embeddings_cache embeddings_cache_model_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.embeddings_cache
    ADD CONSTRAINT embeddings_cache_model_id_fkey FOREIGN KEY (model_id) REFERENCES public.embedding_models(id);


--
-- Name: access_tokens fk_access_tokens_accounts_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.access_tokens
    ADD CONSTRAINT fk_access_tokens_accounts_id FOREIGN KEY (account_id) REFERENCES public.accounts(id) ON DELETE CASCADE;


--
-- Name: accounts_passwords fk_accounts_passwords_accounts_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_passwords
    ADD CONSTRAINT fk_accounts_passwords_accounts_id FOREIGN KEY (account_id) REFERENCES public.accounts(id) ON DELETE CASCADE;


--
-- Name: config_secret_set_entries fk_config_secret_set_entries_resource_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.config_secret_set_entries
    ADD CONSTRAINT fk_config_secret_set_entries_resource_id FOREIGN KEY (resource_id) REFERENCES public.resources(resource_id) ON DELETE CASCADE;


--
-- Name: config_variable_set_entries fk_config_variable_set_entries_resource_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.config_variable_set_entries
    ADD CONSTRAINT fk_config_variable_set_entries_resource_id FOREIGN KEY (resource_id) REFERENCES public.resources(resource_id) ON DELETE CASCADE;


--
-- Name: resource_events fk_resource_events_resource_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resource_events
    ADD CONSTRAINT fk_resource_events_resource_id FOREIGN KEY (resource_id) REFERENCES public.resources(resource_id);


--
-- Name: resource_labels_projection fk_resource_labels_projection_resource_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resource_labels_projection
    ADD CONSTRAINT fk_resource_labels_projection_resource_id FOREIGN KEY (resource_id) REFERENCES public.resources(resource_id) ON DELETE CASCADE;


--
-- Name: flow_events flow_events_flow_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.flow_events
    ADD CONSTRAINT flow_events_flow_id_fkey FOREIGN KEY (flow_id) REFERENCES public.flows(flow_id);


--
-- Name: flows flows_last_event_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.flows
    ADD CONSTRAINT flows_last_event_id_fkey FOREIGN KEY (last_event_id) REFERENCES public.flow_events(event_id);


--
-- Name: oauth_device_codes oauth_device_codes_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.oauth_device_codes
    ADD CONSTRAINT oauth_device_codes_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id) ON DELETE CASCADE;


--
-- Name: task_events task_events_task_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.task_events
    ADD CONSTRAINT task_events_task_id_fkey FOREIGN KEY (task_id) REFERENCES public.tasks(task_id);


--
-- Name: tasks tasks_last_event_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tasks
    ADD CONSTRAINT tasks_last_event_id_fkey FOREIGN KEY (last_event_id) REFERENCES public.task_events(event_id);


--
-- Name: webhook_deliveries webhook_deliveries_subscription_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.webhook_deliveries
    ADD CONSTRAINT webhook_deliveries_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES public.webhook_subscriptions(id);


--
-- Name: webhook_subscription_events webhook_subscription_events_subscription_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.webhook_subscription_events
    ADD CONSTRAINT webhook_subscription_events_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES public.webhook_subscriptions(id);


--
-- PostgreSQL database dump complete
--

