-- THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
--
-- To regenerate this file from existing migrations, use the following command:
-- ```shell
-- make resources-db-schema
-- ```

CREATE UNIQUE INDEX embedding_models_unique_key
    ON embedding_models(provider, name, COALESCE(revision, ''));

CREATE INDEX embeddings_cache_last_seen_idx
  ON embeddings_cache(last_seen_at);

CREATE UNIQUE INDEX idx_access_tokens_account_id_token_name
    ON access_tokens (account_id, token_name)
    WHERE revoked_at IS NULL;

CREATE INDEX idx_account_quota_events_account_type
    ON account_quota_events (account_id, quota_type);

CREATE UNIQUE INDEX idx_account_quota_events_account_type_prev_event
    ON account_quota_events (account_id, quota_type, prev_event_id)
    WHERE prev_event_id IS NOT NULL;

CREATE INDEX idx_account_quota_events_event_time
    ON account_quota_events (event_time);

CREATE UNIQUE INDEX idx_accounts_email ON accounts (LOWER(email));

CREATE UNIQUE INDEX idx_accounts_name ON accounts (LOWER(account_name));

CREATE UNIQUE INDEX idx_accounts_resource_id ON accounts (resource_id);

CREATE INDEX idx_auth_did_secret_keys
    ON did_secret_keys (entity_type, entity_id);

CREATE UNIQUE INDEX idx_auth_did_secret_keys_unique_entity_id
    ON did_secret_keys (entity_id);

CREATE INDEX idx_auth_rebac_properties_entity
    ON auth_rebac_properties (entity_type, entity_id);

CREATE UNIQUE INDEX idx_auth_rebac_properties_entity_property_name
    ON auth_rebac_properties (entity_type, entity_id, property_name);

CREATE INDEX idx_auth_rebac_relations_object_entity
    ON auth_rebac_relations (object_entity_type,
                             object_entity_id);

CREATE UNIQUE INDEX idx_auth_rebac_relations_row
    ON auth_rebac_relations (subject_entity_type,
                             subject_entity_id,
                             object_entity_type,
                             object_entity_id);

CREATE INDEX idx_auth_rebac_relations_subject_entity
    ON auth_rebac_relations (subject_entity_type,
                             subject_entity_id);

CREATE INDEX idx_config_secret_set_entries_account_key
    ON config_secret_set_entries (account_id, secret_key);

CREATE INDEX idx_config_secret_set_entries_resource_id_generation
    ON config_secret_set_entries (resource_id, resource_generation);

CREATE INDEX idx_config_variable_set_entries_account_key
    ON config_variable_set_entries (account_id, variable_key);

CREATE INDEX idx_config_variable_set_entries_resource_id_generation
    ON config_variable_set_entries (resource_id, resource_generation);

CREATE UNIQUE INDEX idx_dataset_data_blocks_by_hash
    ON dataset_data_blocks (dataset_id, block_hash_bin);

CREATE INDEX idx_dataset_data_blocks_latest_event 
    ON dataset_data_blocks (dataset_id, block_ref_name, event_type, sequence_number DESC);

CREATE UNIQUE INDEX idx_dataset_dependencies
    ON dataset_dependencies (upstream_dataset_id, downstream_dataset_id);

CREATE INDEX idx_dataset_dependencies_downstream_dataset_id
    ON dataset_dependencies (downstream_dataset_id);

CREATE INDEX idx_dataset_dependencies_upstream_dataset_id
    ON dataset_dependencies(upstream_dataset_id);

CREATE INDEX idx_dataset_entries_owner_id
    ON dataset_entries (owner_id);

CREATE UNIQUE INDEX idx_dataset_entries_owner_id_dataset_name
    ON dataset_entries (owner_id, LOWER(dataset_name));

CREATE UNIQUE INDEX idx_dataset_key_blocks_by_hash
    ON dataset_key_blocks (dataset_id, block_hash_bin);

CREATE INDEX idx_dataset_key_blocks_latest_event 
    ON dataset_key_blocks (dataset_id, block_ref_name, event_type, sequence_number DESC);

CREATE UNIQUE INDEX idx_dataset_references
    ON dataset_references (dataset_id, block_ref_name);

CREATE UNIQUE INDEX idx_dataset_statistics
    ON dataset_statistics (dataset_id, block_ref_name);

CREATE INDEX idx_fce_latest_per_scope
  ON flow_configuration_events (flow_type, scope_data, event_time DESC);

CREATE INDEX idx_fe_flow_id_event_id
  ON flow_events (flow_id, event_id);

CREATE UNIQUE INDEX idx_flow_configuration_events_binding_prev_event
    ON flow_configuration_events (flow_type, scope_data, prev_event_id)
    WHERE prev_event_id IS NOT NULL;

CREATE UNIQUE INDEX idx_flow_trigger_events_binding_prev_event
    ON flow_trigger_events (flow_type, scope_data, prev_event_id)
    WHERE prev_event_id IS NOT NULL;

CREATE INDEX idx_flows_active_scope_last
  ON flows (
    json_extract(scope_data,'$'),
    flow_type,
    flow_id DESC
  )
  WHERE flow_status <> 'finished';

CREATE INDEX idx_flows_dataset_status_last_event
  ON flows (
    json_extract(scope_data,'$.dataset_id'),
    flow_status,
    last_event_id DESC,
    flow_id DESC
  );

CREATE INDEX idx_flows_initiator_nonsystem ON flows (initiator) WHERE initiator <> '<system>';

CREATE INDEX idx_flows_ready_by_time
  ON flows (scheduled_for_activation_at, flow_id)
  WHERE scheduled_for_activation_at IS NOT NULL
    AND flow_status IN ('waiting','retrying');

CREATE INDEX idx_flows_scope_dataset
  ON flows (json_extract(scope_data,'$.dataset_id'));

CREATE INDEX idx_flows_scope_subscription_id ON flows (json_extract(scope_data,'$.subscription_id'));

CREATE INDEX idx_flows_scope_type
  ON flows (json_extract(scope_data,'$.type'));

CREATE INDEX idx_flows_status_last_event
  ON flows (flow_status, last_event_id DESC, flow_id DESC);

CREATE INDEX idx_fps_dataset_id
  ON flow_process_states (json_extract(scope_data, '$.dataset_id'));

CREATE INDEX idx_fps_dataset_only
  ON flow_process_states (json_extract(scope_data, '$.dataset_id'))
  WHERE json_extract(scope_data, '$.type') = 'Dataset';

CREATE INDEX idx_fps_effective_state
  ON flow_process_states (effective_state);

CREATE INDEX idx_fps_last_attempt_desc
  ON flow_process_states (last_attempt_at DESC);

CREATE INDEX idx_fps_last_failure_desc
  ON flow_process_states (last_failure_at DESC);

CREATE INDEX idx_fps_updates_next
  ON flow_process_states (next_planned_at)
  WHERE flow_type IN ('dev.kamu.flow.dataset.ingest','dev.kamu.flow.dataset.transform');

CREATE INDEX idx_fps_webhook_only
  ON flow_process_states (json_extract(scope_data, '$.dataset_id'))
  WHERE json_extract(scope_data, '$.type') = 'WebhookSubscription';

CREATE INDEX idx_fte_latest_per_scope
  ON flow_trigger_events (flow_type, scope_data, event_time DESC);

CREATE INDEX idx_oauth_device_codes_device_code_expires_at
    ON oauth_device_codes (DATETIME(device_code_expires_at) DESC);

CREATE INDEX idx_outbox_messages_producer_name ON outbox_messages(producer_name);

CREATE INDEX idx_resource_events_resource_id_event_id
    ON resource_events (resource_id, event_id);

CREATE INDEX idx_resource_events_schema_event_id
    ON resource_events (resource_schema, event_id);

CREATE INDEX idx_resource_labels_projection_key_value_resource_id
    ON resource_labels_projection (label_key, label_value, resource_id);

CREATE UNIQUE INDEX idx_resources_account_schema_name_ci
    ON resources (account_id, resource_schema, resource_name);

CREATE INDEX idx_resources_account_schema_updated_at
    ON resources (account_id, resource_schema, updated_at DESC);

CREATE INDEX idx_resources_summary_projection
    ON resources (
        account_id,
        resource_schema,
        json_extract(status, '$.phase')
    )
    WHERE deleted_at IS NULL;

CREATE INDEX idx_task_events_task_id ON task_events (task_id);

CREATE INDEX idx_tasks_dataset_id ON tasks (dataset_id) WHERE dataset_id IS NOT NULL;

CREATE INDEX idx_tasks_task_status ON tasks (task_status) WHERE task_status != 'finished';

CREATE UNIQUE INDEX idx_uniq_accounts_provider_provider_identity_key
    ON accounts (provider, provider_identity_key);

CREATE INDEX idx_webhook_deliveries_subscription_id
  ON webhook_deliveries (subscription_id);

CREATE INDEX idx_webhook_subscription_dataset_status
  ON webhook_subscriptions (dataset_id, status)
  WHERE dataset_id IS NOT NULL;

CREATE INDEX idx_webhook_subscription_events_subscription_id
  ON webhook_subscription_events (subscription_id);

CREATE UNIQUE INDEX uniq_webhook_subscription_label
  ON webhook_subscriptions (dataset_id, label)  -- NULL dataset_id is fine
  WHERE label IS NOT NULL AND status != 'REMOVED';

CREATE TABLE _sqlx_migrations (
    version BIGINT PRIMARY KEY,
    description TEXT NOT NULL,
    installed_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    success BOOLEAN NOT NULL,
    checksum BLOB NOT NULL,
    execution_time BIGINT NOT NULL
);

CREATE TABLE "access_tokens"
(
    id           VARCHAR(36)  NOT NULL PRIMARY KEY,
    token_name   VARCHAR(100) NOT NULL,
    token_hash   BLOB         NOT NULL,
    created_at   TEXT         NOT NULL,
    revoked_at   TEXT,
    last_used_at TEXT,
    account_id   VARCHAR(100) NOT NULL REFERENCES accounts (id) ON DELETE CASCADE
);

CREATE TABLE account_quota_events (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    account_id    TEXT NOT NULL,
    quota_type    TEXT NOT NULL,
    event_type    TEXT NOT NULL,
    event_payload JSONB NOT NULL,
    event_time    TIMESTAMPTZ NOT NULL DEFAULT (CURRENT_TIMESTAMP)
, prev_event_id BIGINT);

CREATE TABLE "accounts" (
    id VARCHAR(100) NOT NULL PRIMARY KEY,
    account_name VARCHAR(100) NOT NULL,
    email VARCHAR(320) NOT NULL,
    display_name VARCHAR(200) NOT NULL,
    account_type TEXT NOT NULL CHECK(account_type IN ('user', 'organization')),
    avatar_url VARCHAR(1000),
    registered_at TIMESTAMP(6) NOT NULL,
    provider VARCHAR(25) NOT NULL,
    provider_identity_key VARCHAR(100) NOT NULL
, resource_id CHAR(36));

CREATE TABLE "accounts_passwords"
(
    password_hash VARCHAR(100) NOT NULL,
    account_id    VARCHAR(100) NOT NULL REFERENCES accounts (id) ON DELETE CASCADE
);

CREATE TABLE auth_rebac_properties
(
    entity_type    VARCHAR(25)  CHECK (entity_type IN ('account', 'dataset')) NOT NULL,
    entity_id      VARCHAR(100) NOT NULL,
    property_name  VARCHAR(50)  NOT NULL,
    property_value VARCHAR(50)  NOT NULL
);

CREATE TABLE auth_rebac_relations
(
    subject_entity_type VARCHAR(25)  CHECK (subject_entity_type IN ('account', 'dataset')) NOT NULL,
    subject_entity_id   VARCHAR(100) NOT NULL,
    relationship        VARCHAR(50)  NOT NULL,
    object_entity_type  VARCHAR(25)  CHECK (object_entity_type IN ('account', 'dataset')) NOT NULL,
    object_entity_id    VARCHAR(100) NOT NULL
);

CREATE TABLE config_secret_set_entries (
    entry_id               CHAR(36) NOT NULL,
    resource_id            CHAR(36) NOT NULL,
    resource_generation    BIGINT NOT NULL,
    account_id             VARCHAR(100) NOT NULL,
    secret_key             VARCHAR(200) NOT NULL,
    value                  BLOB NOT NULL,
    secret_nonce           BLOB NOT NULL,
    created_at             TIMESTAMPTZ NOT NULL,
    updated_at             TIMESTAMPTZ NOT NULL,

    CONSTRAINT fk_config_secret_set_entries_resource_id
        FOREIGN KEY (resource_id) REFERENCES resources(resource_id) ON DELETE CASCADE,

    CONSTRAINT uq_config_secret_set_entries_resource_generation_key
        UNIQUE (resource_id, resource_generation, secret_key)
);

CREATE TABLE config_variable_set_entries (
    entry_id               CHAR(36) NOT NULL,
    resource_id            CHAR(36) NOT NULL,
    resource_generation    BIGINT NOT NULL,
    account_id             VARCHAR(100) NOT NULL,
    variable_key           VARCHAR(200) NOT NULL,
    value                  TEXT NOT NULL,
    created_at             TIMESTAMPTZ NOT NULL,
    updated_at             TIMESTAMPTZ NOT NULL,

    CONSTRAINT fk_config_variable_set_entries_resource_id
        FOREIGN KEY (resource_id) REFERENCES resources(resource_id) ON DELETE CASCADE,

    CONSTRAINT uq_config_variable_set_entries_resource_generation_key
        UNIQUE (resource_id, resource_generation, variable_key)
);

CREATE TABLE dataset_data_blocks (
    dataset_id VARCHAR(100) NOT NULL REFERENCES dataset_entries(dataset_id) ON DELETE CASCADE,
    block_ref_name VARCHAR(50) NOT NULL,
    event_type VARCHAR(30) NOT NULL CHECK (
        event_type IN (
            'AddData',
            'ExecuteTransform'
        )
    ),
    sequence_number INTEGER NOT NULL,
    block_hash_bin BLOB NOT NULL,
    block_hash_hex TEXT GENERATED ALWAYS AS ('f1620' || hex(block_hash_bin)) VIRTUAL NOT NULL,
    block_payload BLOB NOT NULL,
    PRIMARY KEY (dataset_id, block_ref_name, sequence_number)
);

CREATE TABLE dataset_dependencies
(
    -- Note: no foreign keys here, as external orphans are possible in the graph
    upstream_dataset_id   VARCHAR(100) NOT NULL,
    downstream_dataset_id VARCHAR(100) NOT NULL
);

CREATE TABLE "dataset_entries"
(
    dataset_id   VARCHAR(100) NOT NULL PRIMARY KEY,
    owner_id     VARCHAR(100) NOT NULL, /* Diff: without FK to accounts */
    dataset_name VARCHAR(100) NOT NULL,
    created_at   timestamptz  NOT NULL,
    kind         VARCHAR(15)  NOT NULL CHECK (kind IN ('root', 'derivative')),
    owner_name   VARCHAR(100) NOT NULL
);

CREATE TABLE dataset_key_blocks (
    dataset_id VARCHAR(100) NOT NULL REFERENCES dataset_entries(dataset_id) ON DELETE CASCADE,
    block_ref_name VARCHAR(50) NOT NULL,
    event_type VARCHAR(30) NOT NULL CHECK (
        event_type NOT IN (
            'AddData',
            'ExecuteTransform'
        )
    ),
    sequence_number INTEGER NOT NULL,
    block_hash_bin BLOB NOT NULL,
    block_hash_hex TEXT GENERATED ALWAYS AS ('f1620' || hex(block_hash_bin)) VIRTUAL NOT NULL,
    block_payload BLOB NOT NULL,
    PRIMARY KEY (dataset_id, block_ref_name, sequence_number)
);

CREATE TABLE "dataset_references" (
    dataset_id VARCHAR(100) NOT NULL REFERENCES dataset_entries(dataset_id) ON DELETE CASCADE,
    block_ref_name VARCHAR(50) NOT NULL,
    block_hash_bin BLOB NOT NULL,
    block_hash_hex TEXT GENERATED ALWAYS AS ('f1620' || hex(block_hash_bin)) VIRTUAL NOT NULL
);

CREATE TABLE dataset_statistics (
    dataset_id VARCHAR(100) NOT NULL REFERENCES dataset_entries(dataset_id) ON DELETE CASCADE,
    block_ref_name VARCHAR(50) NOT NULL,
    last_pulled TIMESTAMPTZ DEFAULT NULL,
    num_records BIGINT NOT NULL,
    data_size BIGINT NOT NULL,
    checkpoints_size BIGINT NOT NULL
, num_object_links BIGINT NOT NULL DEFAULT 0, object_links_size BIGINT NOT NULL DEFAULT 0);

CREATE TABLE did_secret_keys(
   entity_type  VARCHAR(25)  CHECK (entity_type IN ('account', 'dataset')) NOT NULL,
   entity_id    VARCHAR(100) NOT NULL,
   secret_nonce BLOB NOT NULL,
   secret_key BLOB NOT NULL);

CREATE TABLE embedding_models (
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    provider   TEXT NOT NULL,
    name       TEXT NOT NULL,
    revision   TEXT NULL,
    dims       INTEGER NOT NULL,
    created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE embeddings_cache (
    model_id       INTEGER NOT NULL REFERENCES embedding_models(id),
    input_hash     BLOB NOT NULL,
    input_text     TEXT NOT NULL,
    embedding      BLOB NOT NULL,

    created_at     TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    last_seen_at   TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    hit_count      INTEGER NOT NULL DEFAULT 0,

    PRIMARY KEY (model_id, input_hash)
);

CREATE TABLE flow_activation_links (
    upstream_flow_id   INTEGER     NOT NULL,
    downstream_flow_id INTEGER     NOT NULL,
    activated_at       TIMESTAMPTZ NOT NULL,

    PRIMARY KEY (upstream_flow_id, downstream_flow_id)
);

CREATE TABLE flow_configuration_events (
    event_id INTEGER PRIMARY KEY NOT NULL,
    flow_type VARCHAR(100) NOT NULL,
    scope_data JSONB NOT NULL,
    event_type VARCHAR(50) NOT NULL,
    event_time TIMESTAMPTZ NOT NULL,
    event_payload JSONB NOT NULL
, prev_event_id BIGINT);

CREATE TABLE flow_event_global_counter (
    name TEXT PRIMARY KEY CHECK (name = 'global'),
    val  INTEGER NOT NULL
);

CREATE TABLE flow_events
(
    event_id      INTEGER PRIMARY KEY NOT NULL,
    flow_id       BIGINT NOT NULL REFERENCES flows(flow_id),
    event_type    VARCHAR(50) NOT NULL,
    event_time    TIMESTAMPTZ NOT NULL,
    event_payload JSONB NOT NULL
);

CREATE TABLE flow_ids
(
    flow_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    created_time timestamptz NOT NULL
);

CREATE TABLE flow_process_states (
    scope_data      JSON NOT NULL,
    flow_type       TEXT NOT NULL,

    user_intent   TEXT NOT NULL DEFAULT 'undefined'
        CHECK (user_intent IN ('undefined', 'enabled', 'paused')),

    stop_policy_kind TEXT NOT NULL DEFAULT 'never'
        CHECK (stop_policy_kind IN ('never', 'after_consecutive_failures')),
    stop_policy_data JSON,

    consecutive_failures INTEGER NOT NULL DEFAULT 0,

    last_success_at  TIMESTAMPTZ,
    last_failure_at  TIMESTAMPTZ,
    last_attempt_at  TIMESTAMPTZ,
    next_planned_at  TIMESTAMPTZ,
    auto_stopped_at  TIMESTAMPTZ,

    effective_state  TEXT NOT NULL
        CHECK (effective_state IN ('stopped_auto', 'failing', 'unconfigured', 'paused_manual', 'active')),
    auto_stopped_reason TEXT DEFAULT NULL
        CHECK (auto_stopped_reason IN ('stop_policy', 'unrecoverable_failure')),
        
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    last_applied_flow_system_event_id INTEGER NOT NULL DEFAULT 0, paused_at TIMESTAMPTZ DEFAULT NULL, running_since TIMESTAMPTZ DEFAULT NULL,

    PRIMARY KEY (scope_data, flow_type)
);

CREATE TABLE flow_system_projected_offsets (
    projector TEXT PRIMARY KEY,
    last_event_id BIGINT NOT NULL DEFAULT 0,
    -- Note: no tx_id column needed in SQLite implementation
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE flow_trigger_events (
    event_id INTEGER PRIMARY KEY NOT NULL,
    flow_type VARCHAR(100) NOT NULL,
    scope_data JSONB NOT NULL,
    event_type VARCHAR(50) NOT NULL,
    event_time TIMESTAMPTZ NOT NULL,
    event_payload JSONB NOT NULL
, prev_event_id BIGINT);

CREATE TABLE flows
(
    flow_id BIGINT NOT NULL PRIMARY KEY REFERENCES flow_ids(flow_id),
    initiator VARCHAR(100) NOT NULL,  /* No referential integrity with account_id, as it can system initiator value */
    last_event_id INTEGER
   REFERENCES flow_events(event_id), scheduled_for_activation_at TIMESTAMPTZ, flow_type TEXT NOT NULL, scope_data JSONB NOT NULL, flow_status VARCHAR(10) NOT NULL DEFAULT 'waiting'
    CHECK(flow_status IN ('waiting', 'running', 'finished', 'retrying')));

CREATE TABLE oauth_device_codes
(
    device_code            VARCHAR(36) NOT NULL PRIMARY KEY,
    device_code_created_at TEXT        NOT NULL,
    device_code_expires_at TEXT        NOT NULL,
    token_iat              INTEGER,
    token_exp              INTEGER,
    token_last_used_at     TEXT,
    account_id             VARCHAR(100) REFERENCES accounts (id) ON DELETE CASCADE
);

CREATE TABLE outbox_message_consumptions(
    consumer_name VARCHAR(200) NOT NULL,
    producer_name VARCHAR(200) NOT NULL,
    last_consumed_message_id BIGINT NOT NULL,
    PRIMARY KEY(consumer_name, producer_name)
);

CREATE TABLE outbox_messages(
    message_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    producer_name VARCHAR(200) NOT NULL,
    content_json JSONB NOT NULL,
    occurred_on timestamptz NOT NULL
, 'version' INT);

CREATE TABLE resource_events (
    event_id               INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    resource_id            CHAR(36) NOT NULL,
    resource_schema        TEXT NOT NULL,

    event_time             TIMESTAMPTZ NOT NULL,
    event_type             VARCHAR(100) NOT NULL,
    event_payload          JSONB NOT NULL,

    CONSTRAINT fk_resource_events_resource_id
        FOREIGN KEY (resource_id) REFERENCES resources(resource_id)
);

CREATE TABLE resource_labels_projection (
    resource_id             CHAR(36) NOT NULL,
    label_key               TEXT NOT NULL,
    label_value             TEXT NOT NULL,

    PRIMARY KEY (resource_id, label_key),

    CONSTRAINT fk_resource_labels_projection_resource_id
        FOREIGN KEY (resource_id) REFERENCES resources(resource_id) ON DELETE CASCADE
);

CREATE TABLE resources (
    resource_id            CHAR(36) PRIMARY KEY NOT NULL,
    account_id             VARCHAR(100) NOT NULL,
    resource_schema        TEXT NOT NULL,
    resource_name          VARCHAR(200) NOT NULL COLLATE NOCASE,
    labels                 JSONB NOT NULL,
    annotations            JSONB NOT NULL,

    spec                   JSONB NOT NULL,
    status                 JSONB NULL,

    generation             BIGINT NOT NULL,

    created_at             TIMESTAMPTZ NOT NULL,
    updated_at             TIMESTAMPTZ NOT NULL,
    deleted_at             TIMESTAMPTZ NULL,
    last_event_id          BIGINT NULL
);

CREATE TABLE sqlite_sequence(name,seq);

CREATE TABLE task_events (
    event_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    task_id BIGINT NOT NULL REFERENCES tasks(task_id),
    event_time timestamptz NOT NULL,
    event_type VARCHAR(50) NOT NULL,
    event_payload JSONB NOT NULL
);

CREATE TABLE task_ids (
    task_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    created_time timestamptz NOT NULL
);

CREATE TABLE tasks
(
    task_id BIGINT NOT NULL PRIMARY KEY REFERENCES task_ids(task_id),
    dataset_id VARCHAR(100),
    task_status VARCHAR(10) CHECK (
        task_status IN (
           'queued', 
           'running', 
           'finished'
        )
    ) NOT NULL
, last_event_id INTEGER
   REFERENCES task_events(event_id));

CREATE TABLE web3_auth_eip4361_nonces
(
    wallet_address VARCHAR(100) NOT NULL PRIMARY KEY,
    nonce          VARCHAR(32)  NOT NULL,
    expires_at     TEXT         NOT NULL
);

CREATE TABLE "webhook_deliveries" (
    delivery_id UUID NOT NULL PRIMARY KEY,
    subscription_id UUID NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    request_payload JSONB NOT NULL,
    request_headers JSONB NOT NULL,
    requested_at TIMESTAMPTZ NOT NULL,
    response_code INT2,
    response_body TEXT,
    response_headers JSONB,
    response_at TIMESTAMPTZ,

    CONSTRAINT webhook_deliveries_subscription_id_fkey 
        FOREIGN KEY (subscription_id) REFERENCES webhook_subscriptions(id)
);

CREATE TABLE webhook_subscription_events (
  event_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  subscription_id CHAR(36) NOT NULL REFERENCES webhook_subscriptions(id),
  created_at TIMESTAMPTZ NOT NULL,
  event_type VARCHAR(50) NOT NULL,
  event_payload JSONB NOT NULL
);

CREATE TABLE webhook_subscriptions (
    id CHAR(36) PRIMARY KEY NOT NULL,
    dataset_id VARCHAR(100),
    event_types TEXT NOT NULL, -- Store as a comma-separated string
    status VARCHAR(15) NOT NULL DEFAULT 'UNVERIFIED' CHECK (
        status IN ('UNVERIFIED', 'ENABLED', 'PAUSED', 'UNREACHABLE', 'REMOVED')
    ),
    label VARCHAR(100),
    last_event_id BIGINT -- Must be an event id, but don't create FK loop
);

CREATE TRIGGER embeddings_cache_check_dims_insert
BEFORE INSERT ON embeddings_cache
FOR EACH ROW
BEGIN
    SELECT
      CASE
        WHEN (SELECT dims FROM embedding_models WHERE id = NEW.model_id) IS NULL
          THEN RAISE(ABORT, 'Unknown model_id')
        WHEN length(NEW.embedding) != (SELECT dims FROM embedding_models WHERE id = NEW.model_id) * 4
          THEN RAISE(ABORT, 'Embedding dims mismatch (expected dims * 4 bytes)')
      END;
END;

CREATE TRIGGER embeddings_cache_check_dims_update
BEFORE UPDATE OF model_id, embedding ON embeddings_cache
FOR EACH ROW
BEGIN
    SELECT
      CASE
        WHEN (SELECT dims FROM embedding_models WHERE id = NEW.model_id) IS NULL
          THEN RAISE(ABORT, 'Unknown model_id')
        WHEN length(NEW.embedding) != (SELECT dims FROM embedding_models WHERE id = NEW.model_id) * 4
          THEN RAISE(ABORT, 'Embedding dims mismatch (expected dims * 4 bytes)')
      END;
END;

CREATE TRIGGER fce_assign_event_id
    AFTER INSERT ON flow_configuration_events
BEGIN
    UPDATE flow_event_global_counter SET val = val + 1 WHERE name = 'global';
    UPDATE flow_configuration_events
        SET event_id = (SELECT val FROM flow_event_global_counter WHERE name = 'global')
        WHERE rowid = NEW.rowid;
END;

CREATE TRIGGER fe_assign_event_id
    AFTER INSERT ON flow_events
BEGIN
    UPDATE flow_event_global_counter SET val = val + 1 WHERE name = 'global';
    UPDATE flow_events
        SET event_id = (SELECT val FROM flow_event_global_counter WHERE name = 'global')
        WHERE rowid = NEW.rowid;
END;

CREATE TRIGGER fte_assign_event_id
    AFTER INSERT ON flow_trigger_events
BEGIN
    UPDATE flow_event_global_counter SET val = val + 1 WHERE name = 'global';
    UPDATE flow_trigger_events
        SET event_id = (SELECT val FROM flow_event_global_counter WHERE name = 'global')
        WHERE rowid = NEW.rowid;
END;

CREATE VIEW flow_system_events AS
    SELECT event_id, 'configurations' as source_stream, event_type, event_time, event_payload
        FROM flow_configuration_events

    UNION ALL

    SELECT event_id, 'triggers' as source_stream, event_type, event_time, event_payload
        FROM flow_trigger_events

    UNION ALL

    SELECT event_id, 'flows' as source_stream, event_type, event_time, event_payload
        FROM flow_events