# Note: dangerous setting, but we are getting too many of these:
#   warning: the following packages contain code that will be rejected by a future version of Rust: num-bigint-dig v0.8.4
[future-incompat-report]
frequency = "never"

[unstable]
feature-unification = true

[resolver]
# Reduces recompilation due to feature permutations
# See: https://www.reddit.com/r/rust/comments/1qzvkwf/workspace_feature_permutations_hell/
feature-unification = "workspace"

[alias]
# Reduces recompilations due to invalidated cache between `cargo build` vs. `cargo clippy`
# by separating `target` directories
# See: https://github.com/rust-lang/cargo/issues/9280
#      https://github.com/rust-lang/cargo/issues/15422
#      (no solution, but there is a description of the root cause)
clippy-target-dir = "clippy --target-dir target/clippy"
