FROM kamu/spark:2.4.0


# Logging
ADD log4j.properties /opt/spark/conf/log4j.properties


# GeoSpark
RUN cd /opt/spark/jars && \
    rm -f /opt/spark/jars/geospark-*.jar && \
    wget https://github.com/DataSystemsLab/GeoSpark/releases/download/1.2.0-spark-2.3/geospark-1.2.0.jar && \
    wget https://github.com/DataSystemsLab/GeoSpark/releases/download/1.2.0-spark-2.3/geospark-sql_2.3-1.2.0.jar
