FROM kamu/spark:2.4.0

# Spark's Dockerfile should be patched with
# https://github.com/apache/spark/pull/23898

# GeoSpark
WORKDIR /opt/spark/jars
RUN rm -f /opt/spark/jars/geospark-*.jar
RUN wget https://github.com/DataSystemsLab/GeoSpark/releases/download/1.2.0-spark-2.3/geospark-1.2.0.jar
RUN wget https://github.com/DataSystemsLab/GeoSpark/releases/download/1.2.0-spark-2.3/geospark-sql_2.3-1.2.0.jar

WORKDIR /opt/spark/work-dir
