/*
 * Kamu REST API
 *
 * You are currently running Kamu CLI in the API server mode. For a fully-featured server consider using [Kamu Node](https://docs.kamu.dev/node/).  ## Auth Some operation require an **API token**. Pass `--get-token` command line argument for CLI to generate a token for you.  ## Resources - [Documentation](https://docs.kamu.dev) - [Discord](https://discord.gg/nU6TXRQNXC) - [Other protocols](https://docs.kamu.dev/node/protocols/) - [Open Data Fabric specification](https://docs.kamu.dev/odf/) 
 *
 * The version of the OpenAPI document: 0.233.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SubQuery : Mirrors the structure of [`QueryRequest`] without the `outputs`
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubQuery {
    /// Succinct commitment
    #[serde(rename = "commitment")]
    pub commitment: Box<models::Commitment>,
    /// Inputs that can be used to fully reproduce the query
    #[serde(rename = "input")]
    pub input: Box<models::QueryRequest>,
    /// Signature block
    #[serde(rename = "proof")]
    pub proof: Box<models::Proof>,
    /// Information about processing performed by other nodes as part of this operation
    #[serde(rename = "subQueries")]
    pub sub_queries: serde_json::Value,
}

impl SubQuery {
    /// Mirrors the structure of [`QueryRequest`] without the `outputs`
    pub fn new(commitment: models::Commitment, input: models::QueryRequest, proof: models::Proof, sub_queries: serde_json::Value) -> SubQuery {
        SubQuery {
            commitment: Box::new(commitment),
            input: Box::new(input),
            proof: Box::new(proof),
            sub_queries,
        }
    }
}

