// Copyright Kamu Data, Inc. and contributors. All rights reserved.
//
// Use of this software is governed by the Business Source License
// included in the LICENSE file.
//
// As of the Change Date specified in that file, in accordance with
// the Business Source License, use of this software will be governed
// by the Apache License, Version 2.0.

use std::path::PathBuf;

use sqlx::PgPool;

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

#[test_group::group(resourcegen, database, postgres)]
#[test_log::test(sqlx::test(migrator = "database_common::POSTGRES_MIGRATOR"))]
async fn dump_postgres_schema(pool: PgPool) {
    let db = pool.connect_options();

    let container_runtime = std::env::var("KAMU_CONTAINER_RUNTIME_TYPE_DB")
        .or_else(|_| std::env::var("KAMU_CONTAINER_RUNTIME_TYPE"))
        .unwrap_or_else(|_| "podman".to_string());

    let postgres_image =
        std::env::var("KAMU_POSTGRES_IMAGE").expect("KAMU_POSTGRES_IMAGE must be set");

    let output = std::process::Command::new(container_runtime)
        .args([
            "run",
            "--rm",
            "--network=host",
            "-e",
            &format!("PGPASSWORD={}", db.get_username()),
            &postgres_image,
            "pg_dump",
            "--schema-only",
            "--no-owner",
            "--no-privileges",
            "--no-comments",
            "--host",
            db.get_host(),
            "--port",
            &db.get_port().to_string(),
            "--username",
            db.get_username(),
            "--dbname",
            db.get_database().unwrap(),
        ])
        .output()
        .expect("Failed to run pg_dump via container");

    assert!(
        output.status.success(),
        "pg_dump failed: {}",
        String::from_utf8_lossy(&output.stderr)
    );

    let raw = String::from_utf8(output.stdout).expect("pg_dump output is not UTF-8");
    let schema_ddl = strip_volatile_lines(&raw);

    let mut out_path = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    out_path.push("../../../../../resources/db/schema.postgres.sql");

    std::fs::create_dir_all(out_path.parent().unwrap()).unwrap();
    std::fs::write(&out_path, build_output(&schema_ddl)).unwrap();
}

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

fn strip_volatile_lines(ddl: &str) -> String {
    ddl.lines()
        .filter(|line| {
            !line.starts_with("\\restrict ")
                && !line.starts_with("\\unrestrict ")
                && !line.starts_with("-- Dumped from database version ")
                && !line.starts_with("-- Dumped by pg_dump version ")
        })
        .collect::<Vec<_>>()
        .join("\n")
}

fn build_output(schema_ddl: &str) -> String {
    format!(
        "-- THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n--\n-- To regenerate \
         this file from existing migrations, use the following command:\n-- ```shell\n-- make \
         resources-db-schema\n-- ```\n\n{schema_ddl}"
    )
}

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
