kind: DatasetSnapshot
version: 1
content:
  name: data-room-activity
  kind: Root
  metadata:
  - kind: SetDataSchema
    schema:
      fields:
      - name: offset
        type:
          kind: Int64
      - name: op
        type:
          kind: Int32
      - name: system_time
        type:
          kind: Timestamp
      - name: event_time
        type:
          kind: Timestamp
      - name: activity_type
        type:
          kind: String
      - name: ocl_id
        type:
          kind: String
      - name: path
        type:
          kind: String
      - name: ref
        type:
          kind: String
      - name: version
        type:
          kind: UInt32
      - name: molecule_change_by
        type:
          kind: String
      - name: molecule_access_level
        type:
          kind: String
      - name: content_type
        type:
          kind: Option
          inner:
            kind: String
      - name: content_length
        type:
          kind: UInt64
      - name: content_hash
        type:
          kind: String
      - name: description
        type:
          kind: Option
          inner:
            kind: String
      - name: categories
        type:
          kind: List
          itemType:
            kind: String
      - name: tags
        type:
          kind: List
          itemType:
            kind: String
  - kind: AddPushSource
    sourceName: default
    read:
      kind: NdJson
      schema:
        fields:
        - name: event_time
          type:
            kind: Option
            inner:
              kind: Timestamp
        - name: activity_type
          type:
            kind: String
        - name: ocl_id
          type:
            kind: String
        - name: path
          type:
            kind: String
        - name: ref
          type:
            kind: String
        - name: version
          type:
            kind: UInt32
        - name: molecule_change_by
          type:
            kind: String
        - name: molecule_access_level
          type:
            kind: String
        - name: content_type
          type:
            kind: Option
            inner:
              kind: String
        - name: content_length
          type:
            kind: UInt64
        - name: content_hash
          type:
            kind: String
        - name: description
          type:
            kind: Option
            inner:
              kind: String
        - name: categories
          type:
            kind: List
            itemType:
              kind: Option
              inner:
                kind: String
        - name: tags
          type:
            kind: List
            itemType:
              kind: Option
              inner:
                kind: String
    merge:
      kind: Append
  - kind: SetInfo
    description: Data room activity
    keywords:
    - DeSci
    - BioTech
    - Funding
    - Crypto
  - kind: SetAttachments
    attachments:
      kind: Embedded
      items:
      - path: README.md
        content: |
          # Data room activity

          Dataset containing activity across all project data rooms in single feed.
