// Copyright Kamu Data, Inc. and contributors. All rights reserved.
//
// Use of this software is governed by the Business Source License
// included in the LICENSE file.
//
// As of the Change Date specified in that file, in accordance with
// the Business Source License, use of this software will be governed
// by the Apache License, Version 2.0.

use std::path::PathBuf;

use indoc::formatdoc;

#[test_group::group(resourcegen)]
#[test_log::test(tokio::test)]
async fn update_graphql_schema() {
    let mut schema_path = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    schema_path.push("../../../resources/schema.gql");

    let schema = kamu_adapter_graphql::schema().sdl();
    let file_content = formatdoc! {"
        # THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
        #
        # To regenerate this schema from existing code, use the following command:
        # ```shell
        # make codegen-graphql-schema
        # ```

        {schema}"};

    std::fs::write(&schema_path, file_content).unwrap();
}
