// automatically generated by the FlatBuffers compiler, do not modify



use std::mem;
use std::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::EndianScalar;

pub enum MetadataBlockOffset {}
#[derive(Copy, Clone, Debug, PartialEq)]

pub struct MetadataBlock<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for MetadataBlock<'a> {
    type Inner = MetadataBlock<'a>;
    #[inline]
    fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self {
            _tab: flatbuffers::Table { buf: buf, loc: loc },
        }
    }
}

impl<'a> MetadataBlock<'a> {
    #[inline]
    pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        MetadataBlock {
            _tab: table,
        }
    }
    #[allow(unused_mut)]
    pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
        _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
        args: &'args MetadataBlockArgs<'args>) -> flatbuffers::WIPOffset<MetadataBlock<'bldr>> {
      let mut builder = MetadataBlockBuilder::new(_fbb);
      if let Some(x) = args.prev_block_hash { builder.add_prev_block_hash(x); }
      if let Some(x) = args.block_hash { builder.add_block_hash(x); }
      builder.finish()
    }

    pub const VT_BLOCK_HASH: flatbuffers::VOffsetT = 4;
    pub const VT_PREV_BLOCK_HASH: flatbuffers::VOffsetT = 6;

  #[inline]
  pub fn block_hash(&self) -> Option<&'a str> {
    self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(MetadataBlock::VT_BLOCK_HASH, None)
  }
  #[inline]
  pub fn prev_block_hash(&self) -> Option<&'a str> {
    self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(MetadataBlock::VT_PREV_BLOCK_HASH, None)
  }
}

pub struct MetadataBlockArgs<'a> {
    pub block_hash: Option<flatbuffers::WIPOffset<&'a  str>>,
    pub prev_block_hash: Option<flatbuffers::WIPOffset<&'a  str>>,
}
impl<'a> Default for MetadataBlockArgs<'a> {
    #[inline]
    fn default() -> Self {
        MetadataBlockArgs {
            block_hash: None,
            prev_block_hash: None,
        }
    }
}
pub struct MetadataBlockBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> MetadataBlockBuilder<'a, 'b> {
  #[inline]
  pub fn add_block_hash(&mut self, block_hash: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(MetadataBlock::VT_BLOCK_HASH, block_hash);
  }
  #[inline]
  pub fn add_prev_block_hash(&mut self, prev_block_hash: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(MetadataBlock::VT_PREV_BLOCK_HASH, prev_block_hash);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> MetadataBlockBuilder<'a, 'b> {
    let start = _fbb.start_table();
    MetadataBlockBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<MetadataBlock<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

#[inline]
pub fn get_root_as_metadata_block<'a>(buf: &'a [u8]) -> MetadataBlock<'a> {
  flatbuffers::get_root::<MetadataBlock<'a>>(buf)
}

#[inline]
pub fn get_size_prefixed_root_as_metadata_block<'a>(buf: &'a [u8]) -> MetadataBlock<'a> {
  flatbuffers::get_size_prefixed_root::<MetadataBlock<'a>>(buf)
}

#[inline]
pub fn finish_metadata_block_buffer<'a, 'b>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>,
    root: flatbuffers::WIPOffset<MetadataBlock<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_metadata_block_buffer<'a, 'b>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>, root: flatbuffers::WIPOffset<MetadataBlock<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
