name: test-examples
on:
  # Manual trigger
  workflow_dispatch: {}
  # Automatic trigger after each release
  # Note: Triggers on both successes and failures (see conditional below)
  workflow_run:
    workflows:
      - release
    types:
      - completed
jobs:
  install_script:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linux / amd64
            runs-on: ubuntu-latest
            expected-install-path: /home/runner/.local/bin/kamu
          - name: Linux / arm64
            runs-on: ubuntu-24.04-arm
            expected-install-path: /home/runner/.local/bin/kamu
    name: Test examples / ${{ matrix.name }}
    runs-on: ${{ matrix.runs-on }}
    if: |
      github.event.workflow_run.conclusion == 'success' ||
      github.event.workflow_run.conclusion == null ||
      github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v5
        with:
          # Checkout the same commit that the release was built for (workflow_run)
          # OR default to the current ref
          ref: ${{ github.event.workflow_run.head_sha || github.ref }}
      
      - uses: actions-rs/toolchain@v1

      - name: Install cargo tools
        run: |
          cargo binstall cargo-nextest -y --force --github-token ${{ secrets.GITHUB_TOKEN }}

      - name: Read kamu version
        uses: SebRollen/toml-action@v1.2.0
        id: read_version
        with:
          file: Cargo.toml
          field: workspace.package.version
      
      - name: Install release
        shell: bash
        run: |
          curl -s "https://get.kamu.dev" | \
            KAMU_VERSION=${{ steps.read_version.outputs.value }} \
            sh -s

          echo $(dirname ${{ matrix.expected-install-path }}) >> $GITHUB_PATH

      - name: Run example tests
        run: make test-examples
